title: CV | Zachary C. Durham
description: Resume for Zachary C. Durham
url: https://cv.zacdurham.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
